### ISSUE TITLE
Add slack icon to Header module 

### ISSUE THREAD

**Issue by Newville23** [barranquillajs/bqjs#16]
We need to add Slack link to allow user join the community's Slack .

**Comment by EdgardoRodriguezSolano** [comment]
![captura de pantalla 2018-11-01 a la s 10 05 21 a m](https://user-images.githubusercontent.com/30706016/47860073-b3ce4f80-ddbd-11e8-9ab2-fd019b58fbf2.png)
How would that flow work? I thought this was invitational only.

**Comment by Lenninlasd** [comment]
We can use this link: https://barranquillajs.slack.com/join/shared_invite/enQtNDI1OTYwOTE2MjQwLTJhYWIzOGJhZDQ3NDljYmMyZjNiMzUwYWM0ZGMwYTliMWRhYmQ2ZjVhODM4MjE2OTg4YTEwYTQzMjAzMzA1Mzc
